Helpfile created
serenevoid/kiwi.nvim pull request #16
Opened 2024-02-08 21:24 UTC by mcjvanschaik

I have created a helpfile, because after installation, the first thing I did was type :he kiwi. 

Tried to describe the plugin independently and not to repeat the README file. Also I have specified a difference in using <Enter> in visual mode and in normal mode in the README file as well as in the helpfile.

2024-02-10 04:09 UTC, serenevoid commented on doc/kiwi.nvim.txt
Can you rename the file to kiwi.txt? That's how I have seen it in most other repos. I'm not very sure about the naming conventions. With this change, I can merge this PR

2024-02-10 04:10 UTC, serenevoid requested changes
Rename kiwi.nvim.txt to kiwi.txt

2024-02-10 04:36 UTC, serenevoid commented
#14 #15

2024-02-11 10:25 UTC, mcjvanschaik commented
I have renamed the file and pushed it to my fork. What do I do now? Do I make a new pull request?

2024-02-11 10:32 UTC, serenevoid approved these changes
Nope. The changes will reflect in this PR when you add the changes to your master branch. Thanks for your contribution!

2024-02-11 10:33 UTC, merged